nelmio_api_doc:
    documentation:
        info:
            title: Smart'Flore services
            description: Trails, card species and other details
            version: "0.2.0"
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/?!_error
            - ^/batch
            - ^/trail
            - ^/taxon
            - ^/login
            - ^/register
            - ^/me
            - ^/ping
            - ^/favoris
            - ^/photo
