nelmio_api_doc:
    documentation:
        info:
            title: Smart'Flore services
            description: Trails, card species and other details
            version: "0.1.0"
    areas: # to filter documented areas
        path_patterns:
            - ^/?!_error
            - ^/trail
            - ^/taxon
